In [24]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [26]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test (1).csv
Saving train.csv to train (1).csv

In [27]:
import pandas as pd

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [28]:
train.head()

,Labels,Text,Text_Tag
0,1,Says the Annies List political group supports ...,abortion
1,2,When did the decline of coal start? It started...,"energy,history,job-accomplishments"
2,3,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy
3,1,Health care reform legislation is likely to ma...,health-care
4,2,The economic turnaround started at the end of ...,"economy,jobs"

In [29]:
train = train.dropna()

In [30]:
def convert_label(label):

    if label <= 2:
        return 0   # Fake
    else:
        return 1   # Real

train["label"] = train["Labels"].apply(convert_label)

In [31]:
train["label"].value_counts()

label
0    5761
1    4477
Name: count, dtype: int64

In [32]:
train["content"] = train["Text"] + " " + train["Text_Tag"]

In [33]:
X = train["content"]
y = train["label"]

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english")

X_vector = vectorizer.fit_transform(X)

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vector,
    y,
    test_size=0.2,
    random_state=42
)

In [36]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

In [37]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.568359375

In [38]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.60      0.75      0.67      1174
           1       0.49      0.33      0.39       874

    accuracy                           0.57      2048
   macro avg       0.55      0.54      0.53      2048
weighted avg       0.55      0.57      0.55      2048

In [39]:
print(confusion_matrix(y_test, pred))

[[879 295]
 [589 285]]

In [40]:
def predict_news(text, topic):

    input_data = text + " " + topic

    vector = vectorizer.transform([input_data])

    prediction = model.predict(vector)

    if prediction[0] == 0:
        return "Fake News"
    else:
        return "Real News"

In [41]:
predict_news(
    "The government built a secret alien base",
    "politics"
)

'Fake News'

In [45]:
import joblib

joblib.dump(model, "fake_news_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [46]:
import os
os.listdir()

['.config',
 'train (1).csv',
 'test.csv',
 'train.csv',
 'tfidf_vectorizer.pkl',
 'test (1).csv',
 'fake_news_model.pkl',
 'sample_data']

In [47]:
from google.colab import files

files.download("fake_news_model.pkl")
files.download("tfidf_vectorizer.pkl")